# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    commands:
      - echo "Checking OS..."
      - uname -a
      - cat /etc/os-release || true
      # Install Node.js based on OS
      - if grep -qi 'amzn' /etc/os-release; then
        curl -sL https://rpm.nodesource.com/setup_22.x | bash - &&
        yum install -y nodejs;
        elif grep -qi 'alpine' /etc/os-release; then
        apk add --no-cache nodejs npm;
        elif grep -qi 'ubuntu\|debian' /etc/os-release; then
        curl -fsSL https://deb.nodesource.com/setup_22.x | bash - &&
        apt-get install -y nodejs;
        else
        echo "Unsupported OS"; exit 1;
        fi
  pre_build:
    commands:
      #installs dependencies into the node_modules/ directory
      - npm install --force
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  baseDirectory: build
  files:
    - build/**/*
    - appspec.yml
    - scripts/**/*
