export const Colors = {
  SKY_BLUE: "#0091D5",
  NAVY_BLUE: "#19335A",
  WHITE: "#FFFFFF",
  BLACK: "#181A1B",
  DARK_GRAY: "#6D6D6D", //For Headings
  DIM_LIGHT_GRAY: "#A0A0A0", // BODY COLOR
  LIGHT_GRAY: "#D5D6D7", //LIGHT COLOR FOR ICONS IN WHITE fields
  LIGHT_BLUE_COLOR: "#F5F9FE",
};
